# Generated by Django 5.0.4 on 2024-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='nombre de usuario')),
                ('password', models.CharField(max_length=255, verbose_name='contraseña')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='correo electrónico')),
                ('birth_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('shipping_address', models.TextField(verbose_name='dirección de despacho')),
                ('rol', models.CharField(choices=[('usuario_normal', 'Usuario Normal'), ('administrador', 'Administrador')], max_length=20)),
            ],
        ),
    ]
